### ISSUE TITLE
취약점 DB 상세 페이지 퍼블리싱

### ISSUE THREAD

**Issue by leedo97y** [FlawDetector-team-yes/FlawDetector-team-yes#12]
## TODO

- [x] 취약점 DB 상세 페이지 content 섹션 퍼블리싱
  - [x] 취약점 DB 페이지에서 Link 태그 이용해서 상세 페이지로 이동하게 만들기 
- [x] 테이블 섹션 퍼블리싱
- [x] 비슷한 정보글 섹션 퍼블리싱
- [x] 이미지 경로 수정
