### ISSUE TITLE
검색 엔진 최적화(SEO) 작업

### ISSUE THREAD

**Issue by OH-Neuri** [FlawDetector-team-yes/FlawDetector-team-yes#124]
## TODO
- [x] SEO를 위해 페이지별 메타태그 설정
  - MetaData로 공통된 정보 묶어서 관리
  - favicon 등록 
- [x] 검색 엔진 활설화를 위해 sitemap, robots 생성
- [x] 구글 서치 콘솔에 사이트 등록
   1. <mate> 태그안에 content 값 metadata 값 안에 등록 (✅)
   2. 배포 후 등록 확인 (✅)
   3. URL 검사도구 이용과 sitemap을 제출 적용 (✅)
- [x]  네이버 웹마스터 도구에 사이트 등록
   1. 네이버 서치어드바이저 사이트관리탭 이동
   2. URL 입력 후 사이트 등록
   3. HTML 태그를 선택하고 **`<meta>`**태그 안의 content 값(’427e28…’)을 복사
   4. 메타 데이터를 export 하는 곳에서 **`metadata.verification.other['naver-site-verification']`**에 값 입력  (✅)
    5. 배포 후 서치어드바이저로 돌아가서 소유확인 클릭  (✅)
    6. 목록에서 사이트를 클릭한 후 요청 메뉴 중 **웹 페이지 수집**과 **사이트맵 제출** 적용 (✅)
- [x] Lighthouse 검색엔진점수 개선
