### ISSUE TITLE
크롤링 번역 수정

### ISSUE THREAD

**Issue by ChoiMHMH** [FlawDetector-team-yes/FlawDetector-team-yes#125]
## TODO
- [ ] llama3 번역 다른 모델로 수정
- [ ] 모델 변경 후 완료되면 [취약점 보고서] 이렇게 대괄호 안 내용 추출해서 클립으로 보여줘야함.
- [ ] 핀 된 페이지도 정렬 추가
