### ISSUE TITLE
UI 전체 규격 수정

### ISSUE THREAD

**Issue by leedo97y** [FlawDetector-team-yes/FlawDetector-team-yes#144]
## TODO
- [ ] layout 규격 수정
- [ ] 메인 페이지 규격 수정
- [ ] 마이 페이지 규격 수정
- [ ] 검사 페이지 규격 수정
- [ ] 검사 결과 페이지 규격 수정
- [ ] 취약점 DB 페이지 규격 수정
