### ISSUE TITLE
전체 ui 크기에 반응형 추가 (2xl, xl, lg)

### ISSUE THREAD

**Issue by leedo97y** [FlawDetector-team-yes/FlawDetector-team-yes#161]
## TODO

- 웹 기준으로 전체 크기 수정
- [x] 전체 크기 조정 로직 삭제
  - setFixedZoom 적용된 부분 삭제
- [x] 1536px 이상 -> 2xl 크기 적용
- [ ] 1440px 이상 -> xl 크기 적용
  - 코드 검사 완료 부분 max width 조정 (✅)
- [ ] 1024px 이하, 이상 -> lg 크기 적용
