### ISSUE TITLE
배포 페이지에 CodeMirror theme 적용이 안되는 이슈

### ISSUE THREAD

**Issue by leedo97y** [FlawDetector-team-yes/FlawDetector-team-yes#163]
## TODO 

> 🏁 local에서는 적용되고 배포환경에서는 적용안되는 CodeMirror theme 에러 수정 일지..

- [x] next.config에 아래와 같은 옵션 추가해서 재배포 해보기
  ```js
    experimental: {
      optimizeCss: true,
    },
  ```
- [x] critters 설치 
  - (🔺) Vercel 배포 오류나서 critters 패키지 --save-dev 옵션으로 설치함.
- [x] CodeMirror theme 적용 import 문 수정
  ```js
    import { eclipse } from "@uiw/codemirror-theme-eclipse/esm/index";

    // 기존 import 문은 아래와 같음.
    // import { eclipse } from "@uiw/codemirror-theme-eclipse";
  ```
  - (🔺) 경로 이전 상태 복구해둠.
- [x] asset 파일 경로 이상한거 같아서 next config에 assetPrepix 설정해봄
  - (🔺) 배포 오류로 경로 ./ -> / 으로 수정
  - (🔺) /public/images 안 아이콘들이 로딩이 안되는 오류 발생, 이전 상태로 원복해둠.
- [x] global.css안에 아래와 같이 설정
  ```css
    .cm-content {
      all: unset;
    }
    // .cm-content는 codemirror 콘텐츠 부분 className이다.
  ```
  - (🔺) 위와 같이 적용했으나 아직 theme 적용은 되지 않음.
- [ ] 빌드 캐시 삭제 후 재배포 진행
