### ISSUE TITLE
랜딩 페이지 퍼블리싱

### ISSUE THREAD

**Issue by ChoiMHMH** [FlawDetector-team-yes/FlawDetector-team-yes#2]
## TODO

- [x] 여러개의 원 무늬 배경
- [x] 시맨틱태그로 수정
- [x] 풀페이지 스크롤
- [ ] 맨위로 올라가게 하는 버튼
- [ ] 각 아티클의 제목부분 애니메이션 추가
- [x] 4번째 article 부분 애니메이션
- [x] 랜딩 페이지 퍼블리싱
