### ISSUE TITLE
코드 검사 결과 페이지 퍼블리싱

### ISSUE THREAD

**Issue by OH-Neuri** [FlawDetector-team-yes/FlawDetector-team-yes#20]
## TODO
- [x] 코드 검사 결과 페이지 코드 목록 사이드바 섹션 퍼블리싱
- [x] 코드 검사 결과 페이지 선택한 코드 섹션 퍼블리싱
- [x] 코드 검사 결과 페이지 분석된 결과 섹션 퍼블리싱
