### ISSUE TITLE
랜딩 페이지 변경사항 수정

### ISSUE THREAD

**Issue by ChoiMHMH** [FlawDetector-team-yes/FlawDetector-team-yes#25]
## TODO
- [x] TOP 버튼 스크롤 약간 내려야 생기고 맨 위에서는 사라지게
- [x] 반응형 또는 예쁘게 수정
- [x] 해더 애니메이션
- [x] 디자인 변경된부분 수정
