### ISSUE TITLE
코드 검사 진행 중임을 표시하는 모달 창 퍼블리싱

### ISSUE THREAD

**Issue by OH-Neuri** [FlawDetector-team-yes/FlawDetector-team-yes#28]
## TODO
- [ ] 선택한 파일을 검사할 것인지 확인하는 화면 퍼블리싱
- [ ] 서버와의 비동기 통신 상태를 표시하는 화면 퍼블리싱
- [ ] 검사 결과 확인 버튼을 클릭하면 페이지가 이동하도록 구현
---

서버에서 데이터를 받아야만 화면이 제대로 표시될 수 있을 것 같습니다. 따라서 먼저 서버 통신을 테스트한 후에 화면 작업을 진행할 예정입니다. 화면은 비교적 빠르게 만들 수 있을 것 같습니다.
