### ISSUE TITLE
github OAuth 설정 / DB 설정

### ISSUE THREAD

**Issue by leedo97y** [FlawDetector-team-yes/FlawDetector-team-yes#39]
## TODO

- [x] 로그인 시 계정 정보 가져오기 확인
- [x] 로그인 시 랜딩페이지(’/’)로 리다이렉트 처리
- [x] 헤더에 Logout 버튼 조건부 렌더링 처리
- [x] 랜딩페이지에 ‘파일분석하러가기’ 조건부 렌더링 처리
- [x] 로그아웃 처리
- [x] firebase DB 설정
- [x] firebase user 정보 등록
- nextAuth 세션 유효기간 24시간으로 변경
  - [x] 세션 시간 기본 유효기간으로 수정
