### ISSUE TITLE
로그인 후 Firebase에 사용자 등록 시 GitHub 사용자 정보(owner) 포함하기

### ISSUE THREAD

**Issue by OH-Neuri** [FlawDetector-team-yes/FlawDetector-team-yes#41]
## TODO
- [x] 로그인 시 사용자 정보 확인 및 저장
    - 사용자가 로그인할 때, Firebase에서 해당 사용자의 정보가 없는 경우, GitHub 프로필 이미지 URL에서 숫자 부분(userNumber)을 추출하여 저장
- [x] GitHub API 호출
  - 추출한 userNumber를 사용하여 다음 GitHub API를 호출: https://api.github.com/user/{userNumber}
   - 응답으로 받은 JSON에서 login 값을 추출하여 owner로 저장
- [x] Firebase에 사용자 정보 저장
   - Firebase에 사용자 정보를 저장할 때, owner(GitHub 사용자 이름)를 포함하여 저장
