### ISSUE TITLE
코드 검사 페이지에서 파일 및 폴더 선택과 뒤로가기 기능 구현

### ISSUE THREAD

**Issue by OH-Neuri** [FlawDetector-team-yes/FlawDetector-team-yes#44]
## TODO
- [x] GitHub API 요청을 위한 API 라우트 생성
   - src/app/api/analyze/repository/route.ts
- [x] 페이지 진입 시 src 폴더 데이터 로드 및 바인딩
- [x] FileListItem 컴포넌트 리팩토링
   - 파일과 폴더를 type props로 구분하여 처리
   - 관련 이미지 예시 
      -  ![image](https://github.com/user-attachments/assets/1a950265-1b0f-4e3e-aaf1-9608c7ce0341)
      -  ![image](https://github.com/user-attachments/assets/23238b42-adbf-4a01-b544-6407132e0d34)
- [x] 폴더 선택 기능 구현
   - 폴더 클릭 시 해당 폴더 경로로 GitHub API 요청을 보내고 결과 바인딩
   - FileList 상단에 뒤로 가기 버튼 추가
   - folder 항목이 file 항목보다 먼저 나오도록 데이터 정렬
- [x] 파일 선택 기능 구현
  - 파일 클릭 시 해당 파일 경로로 GitHub API 요청 후 데이터를 바인딩
  - 파일의 내용을 base64로 디코딩하여 {name, sha, content} 형태로 useSelectedFiles의 selectedFiles에 저장
- [x] 뒤로 가기 기능 구현
  - 뒤로 가기 버튼 클릭 시 이전 폴더 경로로 GitHub API 요청을 보내고 결과 바인딩
- [x] 파일 전체 선택 기능 구현
  - `폴더 전체 검사` 에서 `파일 전체 선택` 으로 변경 
  - 파일 GIthub API를 Promise.all로 병렬로 요청하여 동일한 시간에 파일들이 파일 선택 ui로 변경할 수 있게 처리
