### ISSUE TITLE
llm 설정 및 연결

### ISSUE THREAD

**Issue by leedo97y** [FlawDetector-team-yes/FlawDetector-team-yes#54]
## TODO

- [x] llm 설정 / 연결
  - llm dummydata 사용하여 테스팅 완료 
  - @OH-Neuri 님 코드 참고하여 response body 값 수정
  
    > ![response body 값 수정](https://github.com/user-attachments/assets/31011405-161a-4701-98e8-5871f43cae9c)
  - [x] 09/09 (월) llm user_message 수정
    - 메시지 값에 보안취약점 분석 결과 / eslint 수정제안 결과 따로 알려달라고 작성
    - 각각 결과, 수정된 코드, 수정된 부분 라인 번호 포함해서 작성해달라고 요청  

- [x] llm 설정 시 readableStream으로 값이 body 값이 들어와 결과값이 중복되는 문제 발생 및 해결

    > ![readableStream](https://github.com/user-attachments/assets/5798eec8-8f2c-460a-ad5b-9e82020726a3)
    - 문제해결을 위해 아래 참고
    > ![req.body 수정 참고 stackoverflow](https://github.com/user-attachments/assets/7d87ad8e-be6b-43b4-be8b-6ed459dbe922)
    > <img width="345" alt="req.body 수정 참고 디코" src="https://github.com/user-attachments/assets/29deb97c-9e2a-4363-9893-59348433e0cf">
    - 아래와 같이 req.body 코드를 수정하여 해결
    > ![스크린샷 2024-09-02 오후 2 23 45](https://github.com/user-attachments/assets/2d18e2a5-db1c-4176-a21a-0319263dce3b)
