### ISSUE TITLE
web worker 연결

### ISSUE THREAD

**Issue by leedo97y** [FlawDetector-team-yes/FlawDetector-team-yes#58]
## TODO

- [x] progress 수치 계산 및 화면 출력
  - ( ✅ ) setInterval을 사용한 임의의 percent 계산하는 방법
  - (🔺) file size 사용해서 계산하는 방법
    - 비교할 size 값이 없어 한계가 있음.
  - (🔺) byte 계산해서 사용하는 방법
    - 전체 파일의 byte 값을 얻을 수 없어 사용하는데 문제가 있음.
  - (🔺) 요청 header에서 Content-Length 받아와서 계산해주기
    - `transfer-encoding: chunked` 로 정확한 길이 받아오기 어려움.
  - (🔺) ReadableStream 이용해서 chunk 받아와서 계산하기
    - chunk가 1개 안에 2300byte 이런식으로 들어옴
- [x] web worker 설정 / 연결
  - [x] progress 값을 web worker 안에서 받아올 수 있게 하기.
  - [x] next server api worker 안에서 호출
