### ISSUE TITLE
데이터 크롤링 및 DB저장 자동화

### ISSUE THREAD

**Issue by ChoiMHMH** [FlawDetector-team-yes/FlawDetector-team-yes#61]
## TODO
- [x] llama3 토큰값 갱신 자동으로 되게 설정
- [x] 데이터 스키마 정하기
- [x] 파이어베이스에 데이터 한개 먼저 넣어서 기존 데이터는 넣지 않는 것 테스트
- [x] 크롤링 데이터가 업데이트되었을 때만 Firestore를 업데이트
- [x] 깃허브 액션을 사용한 자동화
