### ISSUE TITLE
코드 검사 상태에 따른 indicator 추가

### ISSUE THREAD

**Issue by leedo97y** [FlawDetector-team-yes/FlawDetector-team-yes#66]
## TODO
- [x] FileListItem에 검사 진행 상태에 따른 indicator 추가
  - loading-arrow 아이콘 추가 
- [x] 코드 검사 진행 상태 toast 추가
  - toast ([🔔 Emil Kowalski Sonner](https://sonner.emilkowal.ski/getting-started) 참고)
  - 검사 완료 후 이동 link 추가
  - date format 후 encoding 하는 로직 추가 (링크에 추가)
- [x] 코드 검사 페이지 stateItem 변경된 UI 적용

### 예상은 했지만 파일명 길이에 따라 잘림..

  > ![파일명이 길면..!](https://github.com/user-attachments/assets/4db37596-1171-4902-822f-348c40f87305)

- [x] 파일명 들어가는 부분 크기 정해두고 넘어가면 ...처리하기
