### ISSUE TITLE
코드 검사 결과 페이지 디자인 변경

### ISSUE THREAD

**Issue by leedo97y** [FlawDetector-team-yes/FlawDetector-team-yes#67]
## TODO
- [x] page.tsx 서버컴포넌트 유지를 위해 page 내 file이름이 있는 header 분리
  - 이미지 경로 오류 수정 (✅)
- [x] infobox 파일 위치 변경
  - 현재 결과 페이지에서만 사용함.
  - 수정된 코드 부분 추가 (✅)
  - 코드 복사 버튼 추가 및 로직 추가 (✅)
- [x] infobox UI 수정
  - type을 기준으로 UI를 변경해줌. (security, suggest)
- [x] 사이드바 UI 변경
  - 검사 완료 데이터 연결 (✅)
- [x] ResCodeViewer, FileAnalysisList 를 묶는 div에 사이드바 height추가
  - 사이드바 ref height 적용 (✅)
