### ISSUE TITLE
로그아웃 버튼 수정 및 회원탈퇴 기능 추가

### ISSUE THREAD

**Issue by leedo97y** [FlawDetector-team-yes/FlawDetector-team-yes#70]
## TODO
- [x] 로그아웃 버튼 style 수정
- [x] 마이페이지 로그아웃 버튼 회원탈퇴 로직으로 변경
  - ProfileInfo 컴포넌트를 server 컴포넌트로 변경 (✅)
    - UserProfile 부분과 서버 로직이 있는 부분으로 분리 (✅)
    - 서버 컴포넌트에서 사용할 수 있는 pathname 관련 로직 middleware에 추가 (✅)
  - 기존 마이페이지 로그아웃 버튼 회원탈퇴 버튼 UI 적용 (✅)
  - 회원탈퇴 로직 추가 (✅)
- [x] session 유지 시간 기본 시간(한 달)으로 수정 (✅)
- [x] basic image 없어서 나는 에러 수정 (✅)
  - [https://github.com/vercel/next.js/discussions/18531](https://github.com/vercel/next.js/discussions/18531) 
  - basicUser 이미지 추가
  - 기존에 useState 사용해서 넣어주던 image src 부분 session에서 바로 가져오도록 수정
- [x] 리랜더링이 안돼서 사용자 정보가 없음에도 불구하고 메인페이지로 가지 않는 에러 수정 (✅)
  - server session 값을 client에 props로 넘겨서 session 여부를 추적할 수 있게 해줌.
