### ISSUE TITLE
reposState 추가, fireStore에 user 별 검사 결과 저장

### ISSUE THREAD

**Issue by leedo97y** [FlawDetector-team-yes/FlawDetector-team-yes#88]
## TODO
- [x] 사용자 email 받아오기
  - ModalProvider에서 session 값 받아와서 모달에 넣어주기 (✅)
- [x] users 내부 특정 유저의 doc에 검사 결과 저장하기
  - fireStore에서 사용자 정보와 일치하는 doc 가져오기 (✅)
  - doc에 analyzeFileResult라는 field가 있는지 검사 (✅)
    - X :  analyzeFileResult field 만들고 빈배열 넣어주기
    - O :  analyzeFileResult field에 결과 저장하기
  - analyzeFileResult field에서 repoName 별 비교를 위해 같은 repoName이 있는 배열 요소 값의 index 찾기 (✅)
    - 같은 repoName X : 바로 결과 넣어주기
    - 같은 repoName O : 찾은 index에 있는 배열 요소를 교체해주기
  - updateDoc으로 결과 저장 (✅)
- [x] 저장 검사 결과 스키마 수정
  ```ts
   analyzeFileResult: [{
     repoId: string; // encoding date
     repoName: string; // repo's name
     data: { // file result data
         sha: string; // file id
         name: string; // file name
         content: string; // decoding code
         result: string; // inspection result data
      }]
   }]
  ```
- [x] reposState store 추가

---
### 👾 작은 문제 사항

- [x] reposState 중복되어 들어오는 문제 해결 
  - store 안 비교 수정 로직에서 repoId -> repoName으로 수정 (✅)
- [x] encoding date값이 finish, save currentStep에서 서로 다른 오류 수정
  - saveTime store 생성 (✅)
  - Promise.all() 실행 후, currentStep이 finish로 변경되는 지점에서 검사 완료 시간을 store에 저장 (✅)
  - Promise.all() 실행 후, reposState, analyzeFileResult 모두 업데이트 (✅)

---
### 추가 사항

- [x] currentStep이 save일 경우 모달 액션 추가
  - 저장 후 다음 버튼을 "확인"으로 변경 (✅)
  - 확인 누를 경우 재검사 할 수 있도록 selectedAllFile, analyzeFiles 초기화 (✅)
  - Toast UI 상태에 맞게 변경 (✅)
