### ISSUE TITLE
코드 검사 결과 페이지 검사 결과 데이터 반영

### ISSUE THREAD

**Issue by leedo97y** [FlawDetector-team-yes/FlawDetector-team-yes#92]
## TODO
- [x] 검사 결과 페이지 검사 결과를 받아오기 위한 사용자 정보 관련 / 데이터 형식 수정
- [x] 결과 페이지 링크 연결
  - 진입 시 에러 원인 public 이미지 경로 수정 (✅) 
  - params 로 받아온 id, inspection 으로 fireStore 조회 (✅) 
- [x] fireStore에서 repoName으로 검사 결과 불러오기
  - filename, repoName 적용 (✅) 
  - content 받아와서 넣어주기 (✅) 
  - result 받아오기 (✅) 
- [x] 보안취약점 분석 결과 담을 객체 만들기
  ```ts
    securityRes: [{
      title: string;
      description: string;
      code: string;
      line: number;
    }]
  ``` 
- [x] eslint 수정 제안 담을 객체 만들기
  ```ts
    suggestRes: [{
      title: string;
      description: string;
      code: string;
      line: number;
    }]
  ``` 
- [x] 객체 형식에 맞춰 정규식을 적용하여 넣어주기
  - title 부분 뽑아내기
  - description 부분 뽑아내기
  - 수정된 code 뽑아내기
  - 수정된 line 번호 뽑아내기
- [x] 각 객체 갯수 세서 총계 표시하는 부분에 넣어주기
- [x] 수정된 코드 부분 파일 언어 indicator 추가하기
  - 파일 확장자를 통해 추출해오도록 로직 구성
